In [38]:
import pandas  as pd
import  numpy as np

df=pd.DataFrame({'A':[11,12,12,11,14,11,15,16,15],
                        'time':np.arange('2017-04-22','2017-05-01','1',dtype='datetime64[D]')})
df

A       time
0  11 2017-04-22
1  12 2017-04-23
2  12 2017-04-24
3  11 2017-04-25
4  14 2017-04-26
5  11 2017-04-27
6  15 2017-04-28
7  16 2017-04-29
8  15 2017-04-30

In [27]:
df.sort_values(['A','time']) # 对 uid time  排序

A       time
0  11 2017-04-22
3  11 2017-04-25
5  11 2017-04-27
1  12 2017-04-23
2  12 2017-04-24
4  14 2017-04-26
6  15 2017-04-28
8  15 2017-04-30
7  16 2017-04-29

In [104]:
df['A'].unique()

array([11, 12, 14, 15, 16])

In [40]:
df[df['A']==11]

A       time
0  11 2017-04-22
3  11 2017-04-25
5  11 2017-04-27

In [90]:
COUNT=df['A'].value_counts()
print(COUNT)
print (COUNT.values[0])
print(COUNT.index[0])

11    3
15    2
12    2
14    1
16    1
Name: A, dtype: int64
3
11


In [87]:
for i in range(COUNT.shape[0]):
    print(COUNT.values[i])
    print(COUNT.index[i])

3
11
2
15
2
12
1
14
1
16


In [85]:
COUNT.shape

(5,)

In [17]:
df["pre"]=df['time'].shift(1)
df

A       time        pre
0  11 2017-04-22        NaT
1  12 2017-04-23 2017-04-22
2  12 2017-04-24 2017-04-23
3  11 2017-04-25 2017-04-24
4  14 2017-04-26 2017-04-25
5  11 2017-04-27 2017-04-26
6  15 2017-04-28 2017-04-27
7  16 2017-04-29 2017-04-28
8  15 2017-04-30 2017-04-29

In [34]:
df_2=df.ix[5,:]
df["days"]=(df_2["time"]-df_2["pre"]).days

In [25]:
df

A       time        pre
0  11 2017-04-22        NaT
1  12 2017-04-23        NaT
2  12 2017-04-24 2017-04-23
3  11 2017-04-25        NaT
4  14 2017-04-26 2017-04-26
5  11 2017-04-27 2017-04-22
6  15 2017-04-28        NaT
7  16 2017-04-29 2017-04-29
8  15 2017-04-30 2017-04-28

In [39]:
count=df['A'].value_counts()
df.sort_values(['A','time'])
sort_a="A"
sort_b="time"
for i in range(count.shape[0]):
    value=count.index[i]
#     print(value)
    shift_t=count.values[i]-1
#     print (shift_t)
    df.ix[df[sort_a]==value,"pre"]=df[df[sort_a]==value][sort_b].shift(shift_t)
#     print(df)
    df.ix[df[sort_a]==value,"days"]=(df['time']-df['pre']).dt.days
# print(df)    
# df=df.dropna(how="any")
df

A       time        pre  days
0  11 2017-04-22        NaT   NaN
1  12 2017-04-23        NaT   NaN
2  12 2017-04-24 2017-04-23   1.0
3  11 2017-04-25        NaT   NaN
4  14 2017-04-26 2017-04-26   0.0
5  11 2017-04-27 2017-04-22   5.0
6  15 2017-04-28        NaT   NaN
7  16 2017-04-29 2017-04-29   0.0
8  15 2017-04-30 2017-04-28   2.0

## NUMPY

In [4]:
import numpy as np
values = [1,2,3,6,7,8]
freqs = [2,1,3,2,3,3]

hist, bin_array= np.histogram(values, bins=[1, 4, 7, 10], weights=freqs)
print (hist)
print(bin_array)

[6 2 6]
[ 1  4  7 10]


In [7]:
import pandas as pd
df=pd.DataFrame({'A':[11,12,12,11,14,11,15,16,15],"B":[12,23,34,45,24,24,25,45,36]})
df

A   B
0  11  12
1  12  23
2  12  34
3  11  45
4  14  24
5  11  24
6  15  25
7  16  45
8  15  36

In [10]:
pd.qcut(x=df['A'],q=3)

0        [11, 11.667]
1    (11.667, 14.333]
2    (11.667, 14.333]
3        [11, 11.667]
4    (11.667, 14.333]
5        [11, 11.667]
6        (14.333, 16]
7        (14.333, 16]
8        (14.333, 16]
Name: A, dtype: category
Categories (3, object): [[11, 11.667] < (11.667, 14.333] < (14.333, 16]]